“Run: 1”
/cm/local/apps/slurm/var/spool/job939689/slurm_script: line 23: $'\nconda create --name tpot2env -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job939689/slurm_script: line 27: $'\npip install -r requirements.txt\n': command not found
RunStart
data/167104_True.pkl
  0%|          | 0/5 [00:00<?, ?it/s]Generation:   0%|          | 0/5 [00:00<?, ?it/s]Generation:  20%|██        | 1/5 [00:07<00:30,  7.61s/it]Generation:  40%|████      | 2/5 [00:19<00:30, 10.14s/it]Generation:  60%|██████    | 3/5 [00:28<00:18,  9.41s/it]Generation:  80%|████████  | 4/5 [00:38<00:09,  9.88s/it]Generation: 100%|██████████| 5/5 [00:40<00:00,  7.11s/it]Generation: 100%|██████████| 5/5 [00:40<00:00,  8.17s/it]
/home/hodesse/miniconda3/envs/tpot2env/lib/python3.10/site-packages/sklearn/preprocessing/_data.py:2785: UserWarning: n_quantiles (779) is greater than the total number of samples (463). n_quantiles is set to n_samples.
  warnings.warn(
failed on 
logs
name 'X_train' is not defined
Traceback (most recent call last):
  File "/common/hodesse/hpc_test/TPOT2_ensemble/hpc_test2.py", line 145, in main
    fitted_ensemble, individual_highest_accuracy = create_stacking_clf_gridsearch(est.pareto_front)
  File "/common/hodesse/hpc_test/TPOT2_ensemble/hpc_test2.py", line 75, in create_stacking_clf_gridsearch
    fitted_pipeline = pareto_front.iloc[i, 10].fit(X_train, y_train)
NameError: name 'X_train' is not defined

Traceback (most recent call last):
  File "/common/hodesse/hpc_test/TPOT2_ensemble/hpc_test2.py", line 145, in main
    fitted_ensemble, individual_highest_accuracy = create_stacking_clf_gridsearch(est.pareto_front)
  File "/common/hodesse/hpc_test/TPOT2_ensemble/hpc_test2.py", line 75, in create_stacking_clf_gridsearch
    fitted_pipeline = pareto_front.iloc[i, 10].fit(X_train, y_train)
NameError: name 'X_train' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/common/hodesse/hpc_test/TPOT2_ensemble/hpc_test2.py", line 177, in <module>
    main()
  File "/common/hodesse/hpc_test/TPOT2_ensemble/hpc_test2.py", line 173, in main
    pickle.dump(pipeline_failure_dict, f)
NameError: name 'pipeline_failure_dict' is not defined
srun: error: esplhpc-cp001: task 0: Exited with exit code 1
