“Run: 1”
/cm/local/apps/slurm/var/spool/job939686/slurm_script: line 23: $'\nconda create --name tpot2env -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job939686/slurm_script: line 27: $'\npip install -r requirements.txt\n': command not found
RunStart
data/167104_True.pkl
  0%|          | 0/5 [00:00<?, ?it/s]Generation:   0%|          | 0/5 [00:00<?, ?it/s]Generation:  20%|██        | 1/5 [00:04<00:18,  4.50s/it]Generation:  40%|████      | 2/5 [00:14<00:23,  7.89s/it]Generation:  60%|██████    | 3/5 [00:18<00:12,  6.06s/it]Generation:  80%|████████  | 4/5 [00:22<00:05,  5.36s/it]Generation: 100%|██████████| 5/5 [00:25<00:00,  4.50s/it]Generation: 100%|██████████| 5/5 [00:25<00:00,  5.18s/it]
Traceback (most recent call last):
  File "/common/hodesse/hpc_test/TPOT2_ensemble/hpc_test2.py", line 145, in main
    fitted_ensemble, individual_highest_accuracy = create_stacking_clf_gridsearch(est.pareto_front)
  File "/common/hodesse/hpc_test/TPOT2_ensemble/hpc_test2.py", line 75, in create_stacking_clf_gridsearch
    fitted_pipeline = pareto_front.iloc[i, 10].fit(X_train, y_train)
NameError: name 'X_train' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/common/hodesse/hpc_test/TPOT2_ensemble/hpc_test2.py", line 177, in <module>
    main()
  File "/common/hodesse/hpc_test/TPOT2_ensemble/hpc_test2.py", line 167, in main
    pipeline_failure_dict = {"taskid": taskid,"run": num_runs, "error": str(e), "trace": trace}
NameError: name 'taskid' is not defined. Did you mean: 'task_id'?
srun: error: esplhpc-cp001: task 0: Exited with exit code 1
